apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: webapp-ingress-v1
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
   - host: "*"
     http:
       paths: 
       - backend:
            serviceName: webapp-v1
            servicePort: 80 
         path: /